version: '2'
services:
  nginx:
    image: easyac/nginx:dev
    ports:
      - 8080:80
    links:
      - api:api
  api:
    restart: always
    image: easyac/api
    volumes:
      - "~/dev/easyac/easyac-api:/app"
    depends_on:
      - mongo
      - redis
    links:
      - mongo:mongo
      - redis:redis
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - DEBUG=worker
      - PORT=3000
      - MONGO_URL=mongodb://mongo/easyac
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET="[YteUqD8?HAG{PCkLjYwms3ura[@aJy,@9)wt=x"
  # worker:
  #   restart: always
  #   image: easyac/worker
  #   depends_on:
  #     - redis
  #   links:
  #     - redis:redis
  #   volumes:
  #     - "~/dev/easyac/easyac-workers:/app"
  #   environment:
  #     - NODE_ENV=development
  #     - DEBUG=worker
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  mongo:
    image: mongo
    volumes:
      - "./.data/db:/data/db"
    ports:
      - 27017:27017
  redis:
    image: redis
    ports:
      - 6379:6379
