version: '2'
services:
  api:
    restart: always
    image: easyac/api
    depends_on:
      - mongo
    links:
      - mongo:mongo
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URL=mongodb://mongo/easyac
  mongo:
    image: mongo
    volumes:
      - "./.data/db:/data/db"
    ports:
      - 27017:27017