version: '2'
services:
  nginx:
    image: easyac/nginx
    ports:
      - 8080:80
      - 443:443
    links:
      - api:api
    volumes:
      - "/etc/letsencrypt/archive:/archive"
      - "/etc/letsencrypt/live/api.easyac.xyz-0001:/ssl/api.easyac.xyz"
      - "/etc/letsencrypt/live/docs.easyac.xyz/:/ssl/docs.easyac.xyz"
      - "/etc/letsencrypt/live/easyac.xyz:/ssl/easyac.xyz"
  api:
    restart: always
    image: easyac/api
    depends_on:
      - mongo
    links:
      - mongo:mongo
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URL=mongodb://mongo/easyac
      - JWT_SECRET="[YteUqD8?HAG{PCkLjYwms3ura[@aJy,@9)wt=x"
  mongo:
    image: mongo
    volumes:
      - "./.data/db:/data/db"
    ports:
      - 27017:27017