version: '2'
services:
  nginx:
    image: easyac/nginx
    ports:
      - 8080:80
      - 443:443
    links:
      - api:api
    volumes:
      - "/etc/letsencrypt/archive:/archive"
      - "/etc/letsencrypt/live/api.easyac.xyz-0001:/ssl/api.easyac.xyz"
      - "/etc/letsencrypt/live/docs.easyac.xyz/:/ssl/docs.easyac.xyz"
      - "/etc/letsencrypt/live/easyac.xyz:/ssl/easyac.xyz"
  api:
    restart: always
    image: easyac/api
    volumes:
      - "/home/icaro/dev/easyac/easyac-api:/app"
    depends_on:
      - mongo
      - redis
    links:
      - mongo:mongo
      - redis:redis
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URL=mongodb://mongo/easyac
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET="[YteUqD8?HAG{PCkLjYwms3ura[@aJy,@9)wt=x"
  worker:
    restart: always
    image: easyac/worker
    depends_on:
      - redis
    links:
      - redis:redis
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  mongo:
    image: mongo
    volumes:
      - "./.data/db:/data/db"
    ports:
      - 27017:27017
  redis:
    image: redis
    volumes:
      - "./.data/db:/data/db"
    ports:
      - 6379:6379
