version: '2'
services:
  nginx:
    image: easyac/nginx:dev
    ports:
      - 8080:80
    links:
      - api:api
  api:
    restart: always
    image: easyac/api
    volumes:
      - "~/dev/easyac/api:/app"
      - "/app/node_modules"
    depends_on:
      - mongo
      - redis
    links:
      - mongo:mongo
      - redis:redis
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=${NODE_ENV}
      - DEBUG=api
      - PORT=3000
      - MONGO_URL=mongodb://mongo/easyac
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
  worker:
    restart: always
    image: easyac/worker
    depends_on:
      - redis
    links:
      - redis:redis
    volumes:
      - "~/dev/easyac/workers:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DEBUG=worker
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
  mongo:
    image: mongo
    volumes:
      - "./.data/db:/data/db"
    ports:
      - 27017:27017
  redis:
    image: redis
    ports:
      - 6379:6379
