version: '2'
services:
  nginx:
    restart: always
    image: easyac/nginx:dev
    ports:
      - 8080:80
    links:
      - api:api
  api:
    restart: always
    image: easyac/api
    depends_on:
      - mongo
      - redis
    links:
      - mongo:mongo
      - redis:redis
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - DEBUG=api
      - PORT=3000
      - MONGO_URL=${MONGO_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET="[YteUqD8?HAG{PCkLjYwms3ura[@aJy,@9)wt=x"
  worker:
    restart: always
    image: easyac/worker
    depends_on:
      - redis
    links:
      - redis:redis
    environment:
      - DEBUG=*
      - NODE_ENV=development
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - FGM_KEY=${FGM_KEY}
  mongo:
    image: mongo
    volumes:
      - "./.data/db:/data/db"
    ports:
      - 27017:27017
  redis:
    image: redis
    ports:
      - 6379:6379
