version: '2'
services:
  nginx:
    image: easyac/nginx
    ports:
      - 8080:80
      - 443:443
    links:
      - api:api
    volumes:
      - "/etc/letsencrypt/archive:/archive"
      - "/etc/letsencrypt/live/api.easyac.xyz-0001:/ssl/api.easyac.xyz"
      - "/etc/letsencrypt/live/docs.easyac.xyz/:/ssl/docs.easyac.xyz"
      - "/etc/letsencrypt/live/easyac.xyz:/ssl/easyac.xyz"
  api:
    restart: always
    image: easyac/api
    depends_on:
      - redis
    links:
      - redis:redis
    ports:
      - 3000:3000
    environment:
      - DEBUG=api
      - NODE_ENV=${NODE_ENV}
      - PORT=3000
      - MONGO_URL=${MONGO_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
  worker:
    restart: always
    image: easyac/workers
    depends_on:
      - redis
    links:
      - redis:redis
    environment:
      - DEBUG=worker
      - NODE_ENV=${NODE_ENV}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - FGM_KEY=${FGM_KEY}
  redis:
    image: redis
    ports:
      - 6379:6379
